apiVersion: apps/v1
kind: Deployment
metadata:
    name: dpid-resolver
    labels:
        App: DpidResolver
spec:
    replicas: 2
    revisionHistoryLimit: 2
    selector:
        matchLabels:
            App: DpidResolver
    strategy:
        rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
        type: RollingUpdate
    template:
        metadata:
            annotations:
                vault.hashicorp.com/agent-inject: "true"
                vault.hashicorp.com/agent-inject-status: "update"
                vault.hashicorp.com/role: app-vault-reader
                vault.hashicorp.com/agent-inject-secret-config: secrets/dpid-resolver/production
                vault.hashicorp.com/agent-inject-template-config: |
                    {{- with secret "secrets/dpid-resolver/production" -}}
                    echo "appstart"; 
                    export NODE_ENV={{ .Data.NODE_ENV }}
                    export SUPABASE_URL={{ .Data.SUPABASE_URL }}
                    export SUPABASE_KEY={{ .Data.SUPABASE_KEY }}

                    export DPID_ENV={{ .Data.DPID_ENV }}
                    export IPFS_GATEWAY={{ .Data.IPFS_GATEWAY}}
                    export OPTIMISM_RPC_URL={{ .Data.OPTIMISM_RPC_URL }}
                    export CERAMIC_URL={{ .Data.CERAMIC_URL }}
                    export FALLBACK_RESOLVER={{ .Data.FALLBACK_RESOLVER }}

                    export REDIS_HOST={{ .Data.REDIS_HOST }}
                    export REDIS_PORT={{ .Data.REDIS_PORT }}
                    export CACHE_TTL_ANCHORED={{ .Data.CACHE_TTL_ANCHORED }}
                    export CACHE_TTL_PENDING={{ .Data.CACHE_TTL_PENDING }}
                    echo "loaded"
                    {{- end -}}
            labels:
                App: DpidResolver
        spec:
            containers:
                - image: 523044037273.dkr.ecr.us-east-2.amazonaws.com/dpid-resolver:latest
                  name: dpid-resolver
                  command: ["/bin/bash", "-c"]
                  args:
                      - echo "SOURCING ENV"; source /vault/secrets/config; dumb-init node ./dist/index.js;
                  ports:
                      - containerPort: 5460
                  resources:
                      limits:
                          cpu: "0.5"
                          memory: 512Mi
                      requests:
                          cpu: 250m
                          memory: 50Mi
            serviceAccountName: "vault-auth"
---
apiVersion: v1
kind: Service
metadata:
  name: dpid-resolver-service
  labels:
    App: DpidResolver
spec:
  type: LoadBalancer
  selector:
    App: DpidResolver
  ports:
    - protocol: TCP
      name: api
      port: 80
      targetPort: 5460
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dpid-resolver-ingress
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/target-type: "ip"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    # alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    # alb.ingress.kubernetes.io/ssl-redirect: '443'
    # If you have a certificate for SSL termination at ALB
    # alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:region:account-id:certificate/certificate-id"
spec:
  rules:
  - host: "dpid.org"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dpid-resolver-service
            port:
              number: 80
  - host: "*.dpid.org"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dpid-resolver-service
            port:
              number: 80
