apiVersion: apps/v1
kind: Deployment
metadata:
    name: dpid-resolver
    labels:
        App: DpidResolver
spec:
    replicas: 2
    revisionHistoryLimit: 2
    selector:
        matchLabels:
            App: DpidResolver
    strategy:
        rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
        type: RollingUpdate
    template:
        metadata:
            annotations:
                vault.hashicorp.com/agent-inject: "true"
                vault.hashicorp.com/agent-inject-status: "update"
                vault.hashicorp.com/role: app-vault-reader
                vault.hashicorp.com/agent-inject-secret-config: secrets/dpid-resolver/production
                vault.hashicorp.com/agent-inject-template-config: |
                    {{- with secret "secrets/dpid-resolver/production" -}}
                    echo "appstart"; 
                    export NODE_ENV={{ .Data.NODE_ENV }}
                    export SUPABASE_URL={{ .Data.SUPABASE_URL }}
                    export SUPABASE_KEY={{ .Data.SUPABASE_KEY }}

                    export DPID_ENV={{ .Data.DPID_ENV }}
                    export IPFS_GATEWAY={{ .Data.IPFS_GATEWAY}}
                    export OPTIMISM_RPC_URL={{ .Data.OPTIMISM_RPC_URL }}
                    export CERAMIC_URL={{ .Data.CERAMIC_URL }}
                    echo "loaded"
                    {{- end -}}
            labels:
                App: DpidResolver
        spec:
            containers:
                - image: 523044037273.dkr.ecr.us-east-2.amazonaws.com/dpid-resolver:latest
                  name: dpid-resolver
                  command: ["/bin/bash", "-c"]
                  args:
                      - echo "SOURCING ENV"; source /vault/secrets/config; dumb-init node ./dist/index.js;
                  ports:
                      - containerPort: 5460
                  resources:
                      limits:
                          cpu: "0.5"
                          memory: 512Mi
                      requests:
                          cpu: 250m
                          memory: 50Mi
            serviceAccountName: "vault-auth"
