apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpid-resolver
  labels:
    App: DpidResolver
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      App: DpidResolver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        App: DpidResolver
    spec:
      containers:
        - image: 523044037273.dkr.ecr.us-east-2.amazonaws.com/dpid-resolver:latest
          name: dpid-resolver
          ports:
            - containerPort: 5469
          resources:
            limits:
              cpu: '0.5'
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 50Mi
